config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'experiences#index'

  resources :experiences, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord

  validates_presence_of :name, :rating
  validates :client_ip, presence: true, uniqueness: true

  def self.amount_rating
    Experience.average('rating')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def client_ip
    request.remote_ip
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  # GET experiences/
  def index
    @experiences = Experience.all
    @amount_rating = Experience.amount_rating
  end

  # GET experiences/new
  def new
    @experience = Experience.new
  end

  # POST experiences/
  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      flash[:info] = 'Event added'
    else
      flash[:error] = @experience.errors
    end
    redirect_to experiences_path
  end

  protected

  def experience_params
    params.fetch(:experience).permit(:name, :rating).to_h.merge(client_ip: client_ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <div>
    <label>Name</label>
    <div>
      <%= form.text_field :name %>
    </div>
  </div>
  <div>
    <label>Rating</label>
    <div>
      <%= form.number_field :rating, step: 0.01, max: 5 %>
    </div>
  </div>
  <div>
    <%= form.submit data: {confirm: 'Are you sure?'} %>
  </div>
<% end %>

app/views/experiences/index.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1>Amount Rating: <%=@amount_rating%></h1>
<div>
  <%= button_to "Add", new_experience_path, :method => :get %>
</div>
<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
  </tr>
  <% @experiences.each do |experience| %>
    <tr>
      <td><%= experience.name %></td>
      <td><%= experience.rating %></td>
    </tr>
  <% end %>
</table>

app/views/experiences/new.html.erb
<h1>Create new</h1>
<div>
  <%= render 'form', experience: @experience %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedbackTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>